version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    labels:
      - dependabot
    target-branch: v4
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - dependabot
    target-branch: v4
